project_id = "eokfgqpmghcjzdxgpkql"

[functions.get-maps-key]
verify_jwt = false

[functions.get-directions]
verify_jwt = false

[functions.calculate-fare]
verify_jwt = false

[functions.match-captain]
verify_jwt = false
